import { describe, test } from 'vitest'

describe('ingest > outputs > sync error', () => {
  test.todo('can log a new error', () => {
    // log new error when the sync fails
  })
  test.todo('can update existing error in the database', () => {
    // if you found the same error that is already in the database, the updated_at date should be updated
  })
})
